version: "3.8"

services:
  php:
    container_name: gendel_php
    image: php:8.3.12-zts-bullseye
    # чтобы контейнер не закрывался, временное
    command: tail -f /dev/null
    working_dir: /usr/src/gendel
    volumes:
      - .:/usr/src/gendel

  composer:
    image: composer
    container_name: gendel_composer
    working_dir: /usr/src/gendel
    volumes:
      - .:/usr/src/gendel
    # чтобы контейнер не закрывался, временное
    command: tail -f /dev/null
    depends_on:
      - php