services:
  gendel_db:
    container_name: gendel_db
    image: mysql:8.0.39-debian
    restart: always

    # Чем ниже строчка тем выше приоритет.
    #
    # Не делай так:
    # env_file:
    #  - .env
    #  - .env.local
    # environment:
    #      MYSQL_ROOT_PASSWORD: ${MYSQL_PWD}
    # MYSQL_PWD подятнется только из .env а .env.local будет проигнорирован.
    # То есть если нужно задать переменную окружения, которая должна подятнуться
    # из файлов указанных в env_file, то указывай эту переменную в env-файлах
    # сразу с тем именем, которое требуется и не указывай её здесь в environment
    env_file:
      - .env
      - .env.test.local

  gendel_php:
    container_name: gendel_php
    image: php:8.3.12-zts-bullseye
    # чтобы контейнер не закрывался, временное
    command: tail -f /dev/null
    working_dir: /usr/src/gendel
    volumes:
      - .:/usr/src/gendel

  gendel_composer:
    container_name: gendel_composer
    image: composer
    working_dir: /usr/src/gendel
    volumes:
      - .:/usr/src/gendel
    # чтобы контейнер не закрывался, временное
    command: tail -f /dev/null
    depends_on:
      - gendel_php