services:
  gendel_service_db:
    container_name: $DB_CONTAINER_NAME
    hostname: $DB_HOSTNAME

    # для подключения к БД через БД-viewer в хостовой системе
    ports:
      - "3306:3307"

    image: mysql:8.0.39-debian
    restart: always

    # Чем ниже строчка тем выше приоритет.
    #
    # Не делай так:
    # env_file:
    #  - .env
    #  - .env.local
    # environment:
    #      MYSQL_ROOT_PASSWORD: ${MYSQL_PWD}
    # MYSQL_PWD подтянется только из .env а .env.local будет проигнорирован.
    # То есть если нужно задать переменную окружения, которая должна подтянуться
    # из файлов указанных в env_file, то указывай эту переменную в env-файлах
    # сразу с тем именем, которое требуется и не указывай её здесь в
    # environment.
    env_file:
      - .env
      - .env.test
      - .env.test.local

    volumes:
      - gendel_db_data_volume:/var/lib/mysql

  gendel_service_php:
    container_name: $PHP_CONTAINER_NAME
    build:
      context: .

    # При смене пути не забудь поправить все скрипты из bin, запускающие
    # другие скрипты из bin внутри этого сервиса
    working_dir: /usr/src/gendel

    depends_on:
      - gendel_service_db
    volumes:
      - .:/usr/src/gendel
    command: >
      sh -c " if [ '${APP_ENV}' = 'prod' ]; then
                cp $PHP_INI_DIR/php.ini-production $PHP_INI_DIR/php.ini;
              else
                cp $PHP_INI_DIR/php.ini-development $PHP_INI_DIR/php.ini;
              fi
              # чтобы контейнер не закрывался
              tail -f /dev/null"

  # если будет задана команда в этом сервисе, нужно проверить
  # bin/setup_project_for_dev.sh, так как заданная здесь команда игнорируется перед
  # docker-compose run
  gendel_service_composer:
    container_name: gendel_container_composer
    image: composer
    working_dir: /usr/src/gendel
    volumes:
      - .:/usr/src/gendel

volumes:
  gendel_db_data_volume: